### ISSUE TITLE
Scratch Org creation - Socket timeout

### ISSUE THREAD

**Issue by fischerp** [claimvantage/sfdx-jenkins-shared-library#73] opened 2020-05-06 12:08 UTC
### Summary

I'm getting the error below when creating scratch orgs with an ancestor id defined. It looks like a performance issue on Salesforce side. So the standard timeout doesn't work.

Error: "Socket timeout occurred while listening for results."

I need to increase the waiting 

### Steps To Reproduce:
1.  Create a scratch org with the "ancestorId" defined on your sfdx-project.json file
`{
    "packageDirectories": [
        {
            "path": "force-app",
            "package": "My Package",
            "versionName": "v1",
            "versionNumber": "1.9.0.NEXT",
            "ancestorId": "myPackage@1.8.0-1"
    ...
`

### Expected result

Scratch Org gets created.

### Actual result

Socket timeout occurred while listening for results.

**Comment by fischerp** [comment] 2020-05-06 12:20
I've tried to add "--wait 30" when executing the force:org:create command, however, got another issue.
Error message: "Your query request was running for too long."

JSON error output: 
`{
    "status": 1,
    "name": "QUERY_TIMEOUT",
    "message": "Your query request was running for too long.",
    "exitCode": 1,
    "commandName": "OrgCreateCommand",
    "stack": "QUERY_TIMEOUT: Your query request was running for too long...
`

**Comment by jefersonchaves** [comment] 2020-05-06 13:19
Hey @fischerp: this seems to be a platform issue, have you tried to create a case or a bug in [cli](https://github.com/forcedotcom/cli) project?

**Comment by fischerp** [comment] 2020-05-06 13:42
Hey @jefersonchaves, yes I've created a case and Salesforce is already working on that. 
I didn't report any bug in the cli project. 

This issue has started around May 1st and my first idea to increase the timeout, which didn't work.
I'll update or close this ticket once I receive back a Salesforce position.

**Comment by jefersonchaves** [comment] 2020-05-08 17:51
Have you got any update about it?

**Comment by fischerp** [comment] 2020-05-11 09:45
They are still working on it.

**Comment by jefersonchaves** [comment] 2020-05-12 19:46
I'm closing this issue given you confirmed this is a platform issue. Feel free to add the outcome of the support ticket.

**Closed by jefersonchaves** 2020-05-12 19:46 UTC
Labels: bug
